services:
    svelte-bot:
        container_name: svelte-bot
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        depends_on:
            svelte-bot-db:
                condition: service_healthy
    svelte-bot-db:
        container_name: svelte-bot-db
        restart: always
        build:
            context: ./pocketbase
            dockerfile: Dockerfile
        ports:
            - 127.0.0.1:8319:8090
        volumes:
            - ./pb_data:/app/pb_data
        healthcheck:
            test: ['CMD', 'curl', '-sf', 'http://127.0.0.1:8090/api/health']
            interval: 10s
            timeout: 5s
            retries: 6
