name: Linting

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PNPM
              uses: pnpm/action-setup@v4.1.0

            - name: Setup Node 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://registry.npmjs.org/
                  cache: pnpm

            - name: Install
              run: pnpm install --frozen-lockfile

            - name: Check
              run: pnpm check
